namespace Satisfying.Game
{
    // GENERATED by BuildScript.WriteBuildStamp immediately before each build.
    // Editing this by hand is pointless: the next build overwrites it.
    public static class BuildStamp
    {
        public const string Commit = "49d52c0";
        public const string Built = "2026-08-25 23:16 UTC";
        public const string Branch = "claude/fps-multiplayer-movement-8a2ve0";

        public static string Describe(int protocolVersion)
        {
            string where = string.IsNullOrEmpty(Branch) ? Commit : Commit + " (" + Branch + ")";
            return "build " + where + "   " + Built + "   protocol v" + protocolVersion;
        }
    }
}
